-- Adds the pmms.property_notes table backing the Property Profile "Notes"
-- tab. No SQL was given for this one in the request.
--
-- IMPORTANT: this table already existed in the sandbox project before this
-- script was written (origin unknown -- not created by anything in this
-- conversation), with a slightly different shape than first assumed:
--   - id is `integer generated by default as identity`, not uuid
--   - the category column is named `note_category`, not `category`
--   - the author column is named `author`, not `author_name`
-- The component (PropertyNotesTab.jsx) was written to match this real,
-- already-live schema. This script's CREATE TABLE mirrors it exactly, so
-- running it on a project where the table doesn't exist yet produces the
-- same shape the component expects.
--
-- RLS is explicitly disabled, matching every other pmms table (see
-- disable_rls_new_project.sql) -- new tables in this project default to
-- RLS ON, which silently blocks anon/authenticated reads and hard-fails
-- writes with "new row violates row-level security policy" until this is
-- run (bit us on property_assets/property_compliance/property_documents
-- already, and this table -- despite already existing -- had the same
-- problem).

create table if not exists pmms.property_notes (
  id integer generated by default as identity primary key,
  property_id integer references pmms.properties(id) on delete cascade,
  note_category text,
  note_text text not null,
  author text,
  is_flagged boolean not null default false,
  flag_status text default 'Open',
  created_at timestamptz default now()
);

alter table pmms.property_notes disable row level security;
