-- Logs every real Claude API call made from the Reports page's AI question
-- box (supabase/functions/ai-ask), so cost can be reported by day/week/
-- month. Written only by that edge function (service-role key, bypasses
-- RLS) -- no client-side insert policy exists or should exist. Read-only
-- for PMMS Admins, matching the AI question box's own admin-only gating
-- (a real per-query cost, unlike the old free pattern-matched version).
create table if not exists pmms.ai_usage_log (
  id bigint generated by default as identity primary key,
  staff_id uuid references public.staff(id),
  question text not null,
  answer text,
  model text not null,
  input_tokens integer,
  output_tokens integer,
  -- Null, not 0, when pricing hasn't been configured yet (see
  -- ai_cost_per_million_input_tokens / ai_cost_per_million_output_tokens in
  -- pmms.settings) -- a real query with unknown cost must never silently
  -- report as free.
  cost_usd numeric(10, 6),
  created_at timestamptz not null default now()
);

alter table pmms.ai_usage_log enable row level security;

create policy "Admins can view AI usage log"
  on pmms.ai_usage_log for select
  using (pmms.current_access_level() = 'admin');
