-- Adds pmms.property_rooms and pmms.property_room_history, backing the new
-- Property Profile "Rooms" tab and the "Current Voids" dashboard KPI. No
-- SQL was given for these in the request, so they follow this session's
-- established conventions for new pmms tables:
--   - integer identity ids throughout (explicitly requested this time,
--     unlike the uuid ids used for property_compliance/property_assets/
--     property_documents/property_notes earlier).
--   - RLS explicitly disabled (see disable_rls_new_project.sql) -- new
--     tables in this project default to RLS ON, which blocks reads/writes
--     until this runs (hit every new pmms table this session).

create table if not exists pmms.property_rooms (
  id integer generated by default as identity primary key,
  property_id integer not null references pmms.properties(id) on delete cascade,
  room_name text not null,
  room_type text,
  current_status text not null default 'Occupied',
  tenant_name text,
  void_since date,
  created_at timestamptz default now()
);

create table if not exists pmms.property_room_history (
  id integer generated by default as identity primary key,
  room_id integer not null references pmms.property_rooms(id) on delete cascade,
  action text not null,
  action_date date not null,
  tenant_name text,
  notes text,
  created_at timestamptz default now()
);

alter table pmms.property_rooms disable row level security;
alter table pmms.property_room_history disable row level security;
