-- Adds a login/activity audit trail -- nobody logged in today, only
-- in-ticket actions are audited (pmms.audit_events, which is tightly
-- ticket-scoped and shouldn't be overloaded with ticket-less rows).
--
-- Resolves identity by email, matching every other lookup in this app
-- (App.jsx's fetchProfile, pmms.current_staff_id(), current_access_level())
-- -- NOT via staff.user_id/auth.uid(), which exists in the schema but is
-- confirmed unused/unpopulated everywhere in the real app.

begin;

create table pmms.login_events (
  id         bigint generated by default as identity primary key,
  staff_id   uuid references public.staff (id),
  staff_name text,
  email      text not null,
  event_type text not null check (event_type in ('Signed In', 'Signed Out')),
  user_agent text,
  created_at timestamptz not null default now()
);

alter table pmms.login_events enable row level security;

-- Only Admin/Manager can read the log.
create policy "admin_manager_read" on pmms.login_events
  for select to authenticated
  using (pmms.is_admin_or_manager());

-- Anyone logged in can write their own login/logout event -- checked
-- against their own verified JWT email, not a client-supplied value.
create policy "self_insert" on pmms.login_events
  for insert to authenticated
  with check (email = auth.jwt() ->> 'email');

commit;

notify pgrst, 'reload schema';
