-- New feature: in-app notifications for builders when a job is assigned or
-- reassigned to them. Row-Level Security applied from the start, matching
-- the same per-role model as the rest of the system (requires
-- add_rls_role_helper_functions.sql to already be applied).

create table if not exists pmms.notifications (
  id bigint generated by default as identity primary key,
  staff_id uuid not null references public.staff(id) on delete cascade,
  ticket_id integer references pmms.tickets(id) on delete cascade,
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_staff_id_idx on pmms.notifications(staff_id);

alter table pmms.notifications enable row level security;

drop policy if exists "admin_manager_full_access" on pmms.notifications;
create policy "admin_manager_full_access" on pmms.notifications
  for all to authenticated
  using (pmms.is_admin_or_manager())
  with check (pmms.is_admin_or_manager());

-- Builders can read and mark-as-read only their own notifications. No
-- builder insert policy -- notifications are only ever created by an
-- admin/manager action (assigning or reassigning a ticket).
drop policy if exists "builder_read_own" on pmms.notifications;
create policy "builder_read_own" on pmms.notifications
  for select to authenticated
  using (pmms.current_access_level() = 'builder' and staff_id = pmms.current_staff_id());

drop policy if exists "builder_update_own" on pmms.notifications;
create policy "builder_update_own" on pmms.notifications
  for update to authenticated
  using (pmms.current_access_level() = 'builder' and staff_id = pmms.current_staff_id())
  with check (pmms.current_access_level() = 'builder' and staff_id = pmms.current_staff_id());
