-- Imports the directors' LLO_Managing_Agent_Landlord_Property_Mapping CSV
-- into the columns added by add_property_managing_agent_columns.sql (run
-- that one first). 68 of the CSV's 69 rows matched a real property here by
-- address (after normalising Road/Rd and Street/St abbreviations -- the
-- CSV and pmms.properties don't format addresses the same way); "Not
-- provided" cells became null rather than being stored as literal text;
-- one mangled agency name ("RIGHT HOME LUTON â€“ ARSHAD", a broken en-dash)
-- was corrected to a plain hyphen.
--
-- Left out, needs manual follow-up:
--   - "36 Henley Road, Bedford, MK40 4FT" (landlord: Kulwinder Singh, agent:
--     SMARTMOVE ESTATES) -- no matching property found in pmms.properties
--     at all under any spelling tried. Either not onboarded yet, or the
--     address differs more than a Road/Rd-style abbreviation.
--   - "82 Home Court LU4 9NR" DID match, but its existing landlord_name
--     ("Chuc Gia Khuu") and the CSV's ("Ghuc Gia Khau") don't quite agree --
--     almost certainly the same person (transliteration/typo variance,
--     not a different landlord), left as-is rather than guessed at. The
--     UPDATE below only touches the new managing_agent_* columns, not
--     landlord_name, so this doesn't overwrite anything either way.
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'd0becbd8-567a-4d5c-a6dd-642a14698f16'; -- 147 Crawley Green Road Luton
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'b00b599d-2e2e-4938-81f9-3f2ccb2f3e49'; -- 23 Kent Road Luton LU1 1TJ
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '66a2c25c-ebf6-4c3e-be6f-31d208000d84'; -- 82 Home Court LU4 9NR
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'd0fc9e78-6f9a-4a1a-bcc1-d6031049f0f7'; -- 651 Dunstable Road Luton LU4 8QR
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'a036d11b-6a5d-49f5-8cf6-a53e504083a0'; -- 9 Stoneygate Road Luton
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'd4b9bea7-77b6-4a46-a507-7988778d32df'; -- 89 Eighth Avenue Luton LU3 3DP
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '4204504c-b4c9-4e0c-b6c6-bb6d64851e69'; -- 11 Baden Powell Crescent Towchester NN12 6DS
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '4531e38c-5af6-4601-9be0-164921085201'; -- 2 Minorca Grove Shenley Brook End Milton Keynes MK5 7FU
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '008282f8-5397-433c-b6be-2b35660fe8bb'; -- 151 High Street Luton LU4 9LE
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '66585974-f51a-4dc6-b627-a0d3889a976a'; -- 76 Charlwood Road  LU4 0BU
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'e4ee969a-f5db-4a08-b016-7eb666bcfdd0'; -- 77 Richmond Hill Luton LU2 7JQ
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '01c2741f-c090-4405-b023-f9cd9edea12c'; -- 112 Alexandra Avenue LU3 1HJ
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '58e72895-1ced-4536-b817-f5f9b7762ab9'; -- 307 Dallow Road Luton LU1 1TF
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'cac35d05-4906-402f-a6d0-7e00b34fac5a'; -- 38 Chandos Road Luton  LU4 8EX
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'a33194b7-7ce1-4633-b08c-4f9f2c1800d8'; -- 39 Wickstead Avenue Luton LU4 9DW
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '812c7e04-519e-4f21-ae5d-3aa1e2aef3df'; -- 121 Chelsea Gardens Houghton Regis LU5 5RN
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '5b6a05d6-73b5-4ab4-a8b6-add3a76612bd'; -- 5 Southampton Gardens Luton LU3 3UA
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'a62a030a-3080-4045-8214-63952be089da'; -- 51 St Monicas Avenue Luton LU3 1PJ
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '570bc5a9-9c33-4361-a4b7-ecc5cb8adca9'; -- 56 Beech Avenue Northampton NN3 2JG
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '620bb829-a7b9-4cde-89b1-542ec33f8059'; -- 5 Spencer Road Luton LU3 1JT
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'b0d0a6a9-b48a-4e29-8406-1bc8182ad983'; -- 570A Dunstable Road Luton LU4 8RT
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = 'c86e5161-b48e-4679-9804-aa6b885e14e5'; -- 4 Gayton Close Luton LU3 1TN
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '7607c401-71ea-406f-bd10-be477002ffa3'; -- 39 Lucas Gardens Luton LU3 4BG
update pmms.properties set managing_agent = 'AF RESIDENTIAL', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '6c394aaf-c245-4585-8574-aea25b4e4e36'; -- 86 Beechwood Road Luton LU4 8RP
update pmms.properties set managing_agent = 'HOMELINK PROPERTY SERVICES', managing_agent_contact_name = null, managing_agent_contact_phone = '01234 320040', managing_agent_email = 'checkin@homelinkonline.com', managing_agent_address = '68 Midland Road, Bedford, Bedfordshire, MK40 1QB' where id = '8bbf562e-7912-4ce5-b616-4fd9f7ec9ae1'; -- Flat 29 Bishopstone House Bishopstone Court Ashburnham Road Bedford MK40 1AQ
update pmms.properties set managing_agent = 'HOMELINK PROPERTY SERVICES', managing_agent_contact_name = null, managing_agent_contact_phone = '01234 320040', managing_agent_email = 'checkin@homelinkonline.com', managing_agent_address = '68 Midland Road, Bedford, Bedfordshire, MK40 1QB' where id = 'afbb1956-ce2f-46fa-b5c4-0de44b127f8f'; -- 53 Bents Close Clapham Bedford MK41 6DZ
update pmms.properties set managing_agent = 'HOMELINK PROPERTY SERVICES', managing_agent_contact_name = null, managing_agent_contact_phone = '01234 320040', managing_agent_email = 'checkin@homelinkonline.com', managing_agent_address = '68 Midland Road, Bedford, Bedfordshire, MK40 1QB' where id = 'a82c29d9-31b7-4cdb-9b36-775816774ba2'; -- 25A Ashburnham Rd Bedford MK40 1DX
update pmms.properties set managing_agent = 'HOMELINK PROPERTY SERVICES', managing_agent_contact_name = null, managing_agent_contact_phone = '01234 320040', managing_agent_email = 'checkin@homelinkonline.com', managing_agent_address = '68 Midland Road, Bedford, Bedfordshire, MK40 1QB' where id = 'ac444785-cd89-4d6a-a8e1-cfb4acab4407'; -- 67 Victoria Road Bedford
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '3e3244b9-8bb0-42eb-90c4-94cecc01c2da'; -- 208 Shire House 400 Dallow Road Luton Bedfordshire LU1 1FL
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'c9131ce9-e730-4867-a0ce-a047f2a3007a'; -- 11 Wells Court 106-108 Wellington St Luton LU1 5GA
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '8da86266-5ff5-4dcf-a772-dd4a0994c7c9'; -- 2 Coltsfoot Green Luton Bedfordshire LU4 0XN
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'e5b1cc54-3c8b-4304-8d39-18e7d95daf6c'; -- Flat 15 16 Rothesay road Luton LU1 1QY
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '758669ee-4917-48a0-8cb4-0c455d4bdd4d'; -- 42 Shirley Road Luton Lu1 1NZ
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '3eff4666-f0d9-49cd-8b14-c95fbcbdff47'; -- 4 Norton Rd Luton LU3 2NX
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '081a5806-9140-4beb-affc-9da72a901262'; -- 46 Fredrick street Luton LU2 7QS
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'aa2531da-2576-4752-91b1-672c953f7c3d'; -- 58 Tavistock Street
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'a5caad0a-693b-48b7-a52f-eac280f02678'; -- 118 Unity House 111 Stuart Street LU1 5FW
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'd0816dba-ffaf-480d-b719-8cb7393220bb'; -- 14 Unity House 111 Stuart St Luton LU1 5FW
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '12204b3a-ac8a-4050-bfa6-8c555778cb29'; -- 15 Unity House 111 Stuart Street Luton LU1 5FW
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = '2b6bf802-0287-48e4-8ca7-186685cd6467'; -- 216 Shire House 400 Dallow Rd Luton LU1 1FL
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'b3c4fb89-60e3-4dce-99bf-0ebfdbcb1cab'; -- 8 Unity House 111 Stuart Street Luton Bedfordshire LU1 5FW
update pmms.properties set managing_agent = 'PRESTIGE MOVE', managing_agent_contact_name = 'Sajad Akhtar', managing_agent_contact_phone = '01582 722633 / 07946352468', managing_agent_email = 'saj@prestigemove.co.uk', managing_agent_address = '37 Alma Street, Luton, LU1 2PL' where id = 'a4aeeff0-2353-461c-9ea9-3e1badc24345'; -- Flat 409 Unity House 111 Stuart Street Luton LU1 5FX
update pmms.properties set managing_agent = 'PROPERTY HIVE BEDS LTD', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '48 High Town Road, Luton, LU2 0DE' where id = '77a67205-7d26-42c4-aca0-98b1a6175165'; -- 53 Dumfries Street Luton LU1 5BP
update pmms.properties set managing_agent = 'PROPERTY HIVE BEDS LTD', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '48 High Town Road, Luton, LU2 0DE' where id = 'ee907c44-5023-4850-a297-b0f066062a43'; -- 54 High Street Shefford SG17 5AX
update pmms.properties set managing_agent = 'PROPERTY HIVE BEDS LTD', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '48 High Town Road, Luton, LU2 0DE' where id = 'a2a4f9b8-79f4-4e90-941b-29ab7a1bc808'; -- 7 Kenilworth Road Luton LU1 1DQ
update pmms.properties set managing_agent = 'PROPERTY HIVE BEDS LTD', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '48 High Town Road, Luton, LU2 0DE' where id = '743bb2db-530e-4b86-a6c0-325418c9a5df'; -- 87 Devon Road LU2 0RU
update pmms.properties set managing_agent = 'PROPERTY LINK', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '403a1e39-0fd0-4e2a-af37-4b6400809d73'; -- 37 Farley Lodge 29 Ruthin Close Luton LU1 5EN
update pmms.properties set managing_agent = 'PROPERTY LINK', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '1008f2fa-6d6d-4433-a5b0-0066cf00ac76'; -- 50 Farley Lodge 29 Ruthin Close Luton Bedfordshire LU1 5EN
update pmms.properties set managing_agent = 'PROPERTY LINK', managing_agent_contact_name = null, managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = null where id = '259294df-14d1-4c6d-aff3-a4ad1aefa60b'; -- 78 Russell Rise Luton LU1 5EX
update pmms.properties set managing_agent = 'RIGHT HOME LUTON - ARSHAD', managing_agent_contact_name = 'Arshad Mahmood', managing_agent_contact_phone = '01582 480011', managing_agent_email = null, managing_agent_address = '42 Cheapside, Luton, Bedfordshire, LU1 2HN' where id = '63595e32-9e8a-4067-bcc8-5bd0294d3582'; -- 97 Highbury Road Luton LU3 1AE
update pmms.properties set managing_agent = 'RIGHT HOME LUTON - ARSHAD', managing_agent_contact_name = 'Arshad Mahmood', managing_agent_contact_phone = '01582 480011', managing_agent_email = null, managing_agent_address = '42 Cheapside, Luton, Bedfordshire, LU1 2HN' where id = 'd417313d-210d-4989-85e7-6ef92a5c2378'; -- Flat 1 44 Brantwood Road
update pmms.properties set managing_agent = 'RIGHT HOME LUTON - ARSHAD', managing_agent_contact_name = 'Arshad Mahmood', managing_agent_contact_phone = '01582 480011', managing_agent_email = null, managing_agent_address = '42 Cheapside, Luton, Bedfordshire, LU1 2HN' where id = '52844b2a-79ec-42fa-9ecb-5c264ce2f098'; -- Flat 5 44 Brantwood Road
update pmms.properties set managing_agent = 'RIGHT HOME LUTON - ARSHAD', managing_agent_contact_name = 'Arshad Mahmood', managing_agent_contact_phone = '01582 480011', managing_agent_email = null, managing_agent_address = '42 Cheapside, Luton, Bedfordshire, LU1 2HN' where id = 'b73847d8-a733-4000-892f-bd576b21962f'; -- 151a Ashburnham Road LU1 1JW
update pmms.properties set managing_agent = 'RIGHT HOME LUTON - ARSHAD', managing_agent_contact_name = 'Arshad Mahmood', managing_agent_contact_phone = '01582 480011', managing_agent_email = null, managing_agent_address = '42 Cheapside, Luton, Bedfordshire, LU1 2HN' where id = '3da00c58-da33-4583-9755-a82e256a7705'; -- 28B Spencer Road Luton LU3 1JU
update pmms.properties set managing_agent = 'RIGHT HOMES BEDFORD - SHAHID MAHMOOD - 2 MIDLAND ROAD RECORD', managing_agent_contact_name = 'Shahid Mahmood', managing_agent_contact_phone = '07877870875', managing_agent_email = 'bedford@right-homes.co.uk', managing_agent_address = '2 Midland Road, Bedford, MK40 1QH' where id = '8449f038-2b0f-43ea-bb9a-7991a0ba04b8'; -- 59c Ford End Road Bedford MK40 4JF
update pmms.properties set managing_agent = 'RIGHT HOMES BEDFORD - SHAHID MAHMOOD - 2 MIDLAND ROAD RECORD', managing_agent_contact_name = 'Shahid Mahmood', managing_agent_contact_phone = '07877870875', managing_agent_email = 'bedford@right-homes.co.uk', managing_agent_address = '2 Midland Road, Bedford, MK40 1QH' where id = '4dce3a42-f189-45b2-aed5-05f3e70a170f'; -- 3 Churchville Road Bedford MK42 9PT
update pmms.properties set managing_agent = 'RIGHT HOMES BEDFORD - SHAHID MAHMOOD - 83 MIDLAND ROAD RECORD', managing_agent_contact_name = 'Shahid Mahmood', managing_agent_contact_phone = null, managing_agent_email = 'bedford@right-homes.co.uk', managing_agent_address = '83 Midland Road, Bedford, MK40 1QH' where id = '4e95bc99-81c9-4469-afe3-b813a9f8eaf7'; -- 5 Bassie Close Bedford MK42 9JZ
update pmms.properties set managing_agent = 'RIGHT HOMES BEDFORD - SHAHID MAHMOOD - 83 MIDLAND ROAD RECORD', managing_agent_contact_name = 'Shahid Mahmood', managing_agent_contact_phone = null, managing_agent_email = 'bedford@right-homes.co.uk', managing_agent_address = '83 Midland Road, Bedford, MK40 1QH' where id = '62b15198-0b3a-4f60-8e2b-9ed1d5304b27'; -- Flat D 51 De Parys Avenue Bedford MK40 2TR
update pmms.properties set managing_agent = 'RIGHT HOMES BEDFORD - SHAHID MAHMOOD - 83 MIDLAND ROAD RECORD', managing_agent_contact_name = 'Shahid Mahmood', managing_agent_contact_phone = null, managing_agent_email = 'bedford@right-homes.co.uk', managing_agent_address = '83 Midland Road, Bedford, MK40 1QH' where id = 'f193cce3-fc50-44ff-aa3c-3a7c8733351d'; -- 60 Plover Way Bedford MK41 7HU
update pmms.properties set managing_agent = 'RIGHT HOMES - RASHID', managing_agent_contact_name = 'Rashid', managing_agent_contact_phone = '07947153909', managing_agent_email = null, managing_agent_address = '11 Curzon Road, Luton, LU3 1BG' where id = 'ba7af8de-71e4-42a4-922c-9c266b30f9f2'; -- 90 Leicester Road Luton LU4 8SJ
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = 'f7582623-02fe-4f29-85a1-bc7a6012f044'; -- 88c Ampthill Road Bedford MK42 9JA
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '95b1e9d4-d049-4b6c-9817-5e44fb7f8f88'; -- 43 Edward Road Bedford MK42 9DR
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '0b4289e5-4499-4df5-ac79-dfd0bcf907b1'; -- 7b Rutland Road Bedford MK40 1DG
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '523ce864-1b65-4fda-aa80-d08877bb67b8'; -- Flat 1 St. Marys Mews 3 Cardington Road Bedford MK42 0BN
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '1fce4b36-1882-461e-8dc5-e52e0dddb317'; -- Ground Floor Flat 2 St Leonards Avenue Bedford MK42 0RB
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '14f0a671-47e8-46ff-b0f1-0f9560234529'; -- 1 Woodstock Road Bedford MK40 4JY
update pmms.properties set managing_agent = 'SMARTMOVE ESTATES', managing_agent_contact_name = 'Sameer Khan', managing_agent_contact_phone = null, managing_agent_email = null, managing_agent_address = '74 Midland Road, Bedford, Bedfordshire, MK40 1QH' where id = '7e8a1595-3322-4099-a3e7-91651918c509'; -- 59 High Street Harrold Bedford MK43 7BH
update pmms.properties set managing_agent = 'ZII PROPERTY MANAGEMENT LTD', managing_agent_contact_name = 'Zainab Padhani-Samii', managing_agent_contact_phone = '07706442845', managing_agent_email = 'z_samii@hotmail.com', managing_agent_address = '94 Whitchurch Gardens, Edgware, England, HA8 6PB' where id = '7dc46794-9198-4022-99d1-a9c0f205f9bd'; -- 9 Adonis Court Admiral Drive

notify pgrst, 'reload schema';
