-- Recreates the pmms schema (+ the public.staff table it depends on) in a
-- fresh Supabase project. RLS is intentionally left disabled on every table
-- (sandbox decision) -- add policies later if you start testing auth-gated
-- access rules.
--
-- Run this whole script once in the new project's SQL Editor.

create schema if not exists pmms;

-- ---------------------------------------------------------------------------
-- public.staff
-- ---------------------------------------------------------------------------
create table public.staff (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  email               text,
  job_title           text,
  department          text,
  role                text default 'sw',
  active              boolean default true,
  created_at          timestamptz default now(),
  must_reset_password boolean default false,
  photo_url           text,
  user_id             uuid default auth.uid()
);

grant usage on schema public to anon, authenticated, service_role;
grant all on public.staff to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- pmms.staff  (kept for structural parity with the source project; not
-- currently referenced by any app code -- everything points at public.staff)
-- ---------------------------------------------------------------------------
create table pmms.staff (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  email      text not null,
  role       text not null,
  title      text,
  phone      text,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- pmms.properties
-- ---------------------------------------------------------------------------
create table pmms.properties (
  id                   integer generated by default as identity primary key,
  address              text not null,
  property_type        text,
  electrical_shutoff   text,
  gas_shutoff          text,
  safeguards           text,
  high_vulnerability   boolean default false,
  vulnerability_reason text,
  created_at           timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- pmms.tickets
-- ---------------------------------------------------------------------------
create table pmms.tickets (
  id                  integer generated by default as identity primary key,
  property_id         integer references pmms.properties (id),
  assigned_builder_id uuid,                          -- no FK in the source project either; matches as-is
  status              text not null default 'Assigned',
  category            text,
  description         text,
  room                text,
  priority_score      integer default 0,
  suppressed          boolean default false,
  force_top           boolean default false,
  reported_by         text,
  hold_reason         text,
  hold_note           text,
  no_access_flag      boolean default false,
  mileage_logged      numeric default 0,
  transit_start       text,
  gps_coordinates     text,
  completion_note     text,
  completed_at        timestamptz,
  created_at          timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- pmms.comments
-- ---------------------------------------------------------------------------
create table pmms.comments (
  id          integer generated by default as identity primary key,
  ticket_id   integer references pmms.tickets (id),
  author_id   uuid references public.staff (id),   -- fixed to public.staff from the start
  author_name text not null,
  role        text,
  body        text not null,
  created_at  timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- pmms.work_sessions
-- ---------------------------------------------------------------------------
create table pmms.work_sessions (
  id         integer generated by default as identity primary key,
  ticket_id  integer references pmms.tickets (id),
  builder_id uuid references public.staff (id),    -- fixed to public.staff from the start
  started_at timestamptz not null,
  ended_at   timestamptz
);

-- ---------------------------------------------------------------------------
-- pmms.audit_events
-- ---------------------------------------------------------------------------
create table pmms.audit_events (
  id         integer generated by default as identity primary key,
  ticket_id  integer references pmms.tickets (id),
  actor_id   uuid references public.staff (id),    -- fixed to public.staff from the start
  actor_name text,
  action     text not null,
  summary    text,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Grants: PostgREST/anon/authenticated need explicit access to a new schema
-- ---------------------------------------------------------------------------
grant usage on schema pmms to anon, authenticated, service_role;

grant all on all tables in schema pmms to anon, authenticated, service_role;
grant all on all sequences in schema pmms to anon, authenticated, service_role;

alter default privileges in schema pmms grant all on tables to anon, authenticated, service_role;
alter default privileges in schema pmms grant all on sequences to anon, authenticated, service_role;
